apiVersion: v1
kind: Secret
metadata:
  name: tgo-object-storage-secret
  namespace: tgo
type: Opaque
stringData:
  minio-access-key-id: REPLACE_ME
  minio-secret-access-key: REPLACE_ME
  oss-access-key-id: REPLACE_ME
  oss-access-key-secret: REPLACE_ME
  s3-access-key: REPLACE_ME
  s3-secret-key: REPLACE_ME
