apiVersion: v1
kind: Secret
metadata:
  name: tgo-redis
  namespace: tgo
type: Opaque
stringData:
  url-db0: redis://:REPLACE_ME@redis.example.com:6379/0
  url-db1: redis://:REPLACE_ME@redis.example.com:6379/1
  url-db2: redis://:REPLACE_ME@redis.example.com:6379/2
  url-db3: redis://:REPLACE_ME@redis.example.com:6379/3
