apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wkim-wukongim-ws
  namespace: wukongim
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: tgo-im.dr-coffee.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wkim-wukongim-local
                port:
                  number: 5200
  tls:
    - hosts:
        - tgo-im.dr-coffee.cn
      secretName: tgo-im-tls
