apiVersion: v1
kind: Secret
metadata:
  name: tgo-postgres
  namespace: dr-coffee-test
type: Opaque
stringData:
  host: gp-bp15zye52b5p658rho-master.gpdb.rds.aliyuncs.com
  port: "5432"
  database: tgo
  username: drcoffee
  password: "StnGAG9#jv4W)a)_srp7"
  database-url: "postgresql+asyncpg://drcoffee:StnGAG9%23jv4W)a)_srp7@gp-bp15zye52b5p658rho-master.gpdb.rds.aliyuncs.com:5432/tgo"
