apiVersion: v1
kind: Secret
metadata:
  name: tgo-postgres
  namespace: dr-coffee-test
type: Opaque
stringData:
  host: pgm-bp1v1i5vq0404lb5.pg.rds.aliyuncs.com
  port: "5432"
  database: tgo
  username: super
  password: "daD(*&dads2221HW"
  database-url: "postgresql+asyncpg://super:daD%28%2A%26dads2221HW@pgm-bp1v1i5vq0404lb5.pg.rds.aliyuncs.com:5432/tgo"
