apiVersion: v1
kind: Secret
metadata:
  name: tgo-redis
  namespace: dr-coffee-test
type: Opaque
stringData:
  host: r-bp1im3chdltyidc90w.redis.rds.aliyuncs.com
  port: "6379"
  username: testcluster
  password: "SSC@wssa!Qq"
  url-db0: "redis://testcluster:SSC%40wssa!Qq@r-bp1im3chdltyidc90w.redis.rds.aliyuncs.com:6379/0"
