apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tgo-widget-js
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - widget.example.com
      secretName: tgo-widget-js-tls
  rules:
    - host: widget.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tgo-widget-js
                port:
                  name: http
