apiVersion: v1
kind: Service
metadata:
  name: tgo-plugin-runtime
  namespace: dr-coffee-test
spec:
  type: ClusterIP
  selector:
    app: tgo-plugin-runtime
  ports:
    - name: http
      port: 8090
      targetPort: http
