apiVersion: v1
kind: Secret
metadata:
  name: tgo-api-secret
  namespace: tgo
type: Opaque
stringData:
  SECRET_KEY: REPLACE_ME_API_SECRET_KEY
  RAG_SERVICE_API_KEY: ""
  AI_SERVICE_API_KEY: ""
  PLATFORM_SERVICE_API_KEY: ""
