apiVersion: v1
kind: Service
metadata:
  name: tgo-api
spec:
  selector:
    app: tgo-api
  ports:
    - name: http
      port: 8000
      targetPort: http
    - name: internal
      port: 8001
      targetPort: internal
