apiVersion: v1
kind: ConfigMap
metadata:
  name: tgo-web-config
  namespace: dr-coffee-test
data:
  VITE_API_BASE_URL: https://tgo-api.dr-coffee.cn
  VITE_DEBUG_MODE: "false"
  VITE_WIDGET_PREVIEW_URL: https://tgo-widget.dr-coffee.cn/
  VITE_WIDGET_SCRIPT_BASE: https://tgo-widget.dr-coffee.cn/tgo-widget-sdk.js
  VITE_WIDGET_DEMO_URL: https://tgo-widget.dr-coffee.cn/demo.html
  VITE_DISABLE_WEBSOCKET_AUTO_CONNECT: "false"
  VITE_STORE_API_URL: https://store.dr-coffee.cn/api/v1
