apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tgo
resources:
  - ../namespace.yaml
  - tgo-rag-job.yaml
  - tgo-ai-job.yaml
  - tgo-api-job.yaml
  - tgo-platform-job.yaml
  - tgo-workflow-job.yaml
  - tgo-plugin-runtime-job.yaml
  - tgo-device-control-job.yaml
