apiVersion: v1
kind: Secret
metadata:
  name: tgo-app-secrets
  namespace: dr-coffee-test
type: Opaque
stringData:
  SECRET_KEY: 8NvCnXkuxxw3rYJugVwJ+o2yRA9MgkTrYtNZWFCYnNoDQtVc6Nr5lHzNE3TB1Srl
  QWEN3_API_KEY: "sk-e8c32602d95741b0b7c6a94a38ece538:"
